In [75]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from datetime import datetime

In [76]:
df = pd.read_csv("./CAR DETAILS FROM CAR DEKHO.csv")
df

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner
...,...,...,...,...,...,...,...,...
4335,Hyundai i20 Magna 1.4 CRDi (Diesel),2014,409999,80000,Diesel,Individual,Manual,Second Owner
4336,Hyundai i20 Magna 1.4 CRDi,2014,409999,80000,Diesel,Individual,Manual,Second Owner
4337,Maruti 800 AC BSIII,2009,110000,83000,Petrol,Individual,Manual,Second Owner
4338,Hyundai Creta 1.6 CRDi SX Option,2016,865000,90000,Diesel,Individual,Manual,First Owner
4339,Renault KWID RXT,2016,225000,40000,Petrol,Individual,Manual,First Owner

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           4340 non-null   object
 1   year           4340 non-null   int64
 2   selling_price  4340 non-null   int64
 3   km_driven      4340 non-null   int64
 4   fuel           4340 non-null   object
 5   seller_type    4340 non-null   object
 6   transmission   4340 non-null   object
 7   owner          4340 non-null   object
dtypes: int64(3), object(5)
memory usage: 271.4+ KB

In [78]:
df.isnull().sum()

name             0
year             0
selling_price    0
km_driven        0
fuel             0
seller_type      0
transmission     0
owner            0
dtype: int64

In [79]:
df["Car_Age"] = datetime.now().year - df["year"]
df.drop(columns=["year", "name"], inplace=True)
df

,selling_price,km_driven,fuel,seller_type,transmission,owner,Car_Age
0,60000,70000,Petrol,Individual,Manual,First Owner,18
1,135000,50000,Petrol,Individual,Manual,First Owner,18
2,600000,100000,Diesel,Individual,Manual,First Owner,13
3,250000,46000,Petrol,Individual,Manual,First Owner,8
4,450000,141000,Diesel,Individual,Manual,Second Owner,11
...,...,...,...,...,...,...,...
4335,409999,80000,Diesel,Individual,Manual,Second Owner,11
4336,409999,80000,Diesel,Individual,Manual,Second Owner,11
4337,110000,83000,Petrol,Individual,Manual,Second Owner,16
4338,865000,90000,Diesel,Individual,Manual,First Owner,9
4339,225000,40000,Petrol,Individual,Manual,First Owner,9

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   selling_price  4340 non-null   int64
 1   km_driven      4340 non-null   int64
 2   fuel           4340 non-null   object
 3   seller_type    4340 non-null   object
 4   transmission   4340 non-null   object
 5   owner          4340 non-null   object
 6   Car_Age        4340 non-null   int64
dtypes: int64(3), object(4)
memory usage: 237.5+ KB

In [81]:
df['fuel'].unique()

array(['Petrol', 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [82]:
df['seller_type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [83]:
df['transmission'].unique()

array(['Manual', 'Automatic'], dtype=object)

In [84]:
df['owner'].unique()

array(['First Owner', 'Second Owner', 'Fourth & Above Owner',
       'Third Owner', 'Test Drive Car'], dtype=object)

In [85]:
df["owner"] = LabelEncoder().fit_transform(df["owner"])
df

,selling_price,km_driven,fuel,seller_type,transmission,owner,Car_Age
0,60000,70000,Petrol,Individual,Manual,0,18
1,135000,50000,Petrol,Individual,Manual,0,18
2,600000,100000,Diesel,Individual,Manual,0,13
3,250000,46000,Petrol,Individual,Manual,0,8
4,450000,141000,Diesel,Individual,Manual,2,11
...,...,...,...,...,...,...,...
4335,409999,80000,Diesel,Individual,Manual,2,11
4336,409999,80000,Diesel,Individual,Manual,2,11
4337,110000,83000,Petrol,Individual,Manual,2,16
4338,865000,90000,Diesel,Individual,Manual,0,9
4339,225000,40000,Petrol,Individual,Manual,0,9

In [86]:
df = pd.get_dummies(df, columns=["fuel", "seller_type", "transmission"], drop_first=True).astype(int)
df

,selling_price,km_driven,owner,Car_Age,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual
0,60000,70000,0,18,0,0,0,1,1,0,1
1,135000,50000,0,18,0,0,0,1,1,0,1
2,600000,100000,0,13,1,0,0,0,1,0,1
3,250000,46000,0,8,0,0,0,1,1,0,1
4,450000,141000,2,11,1,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...
4335,409999,80000,2,11,1,0,0,0,1,0,1
4336,409999,80000,2,11,1,0,0,0,1,0,1
4337,110000,83000,2,16,0,0,0,1,1,0,1
4338,865000,90000,0,9,1,0,0,0,1,0,1
4339,225000,40000,0,9,0,0,0,1,1,0,1

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4340 entries, 0 to 4339
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   selling_price                 4340 non-null   int64
 1   km_driven                     4340 non-null   int64
 2   owner                         4340 non-null   int64
 3   Car_Age                       4340 non-null   int64
 4   fuel_Diesel                   4340 non-null   int64
 5   fuel_Electric                 4340 non-null   int64
 6   fuel_LPG                      4340 non-null   int64
 7   fuel_Petrol                   4340 non-null   int64
 8   seller_type_Individual        4340 non-null   int64
 9   seller_type_Trustmark Dealer  4340 non-null   int64
 10  transmission_Manual           4340 non-null   int64
dtypes: int64(11)
memory usage: 373.1 KB

In [88]:
X = df.drop(columns=["selling_price"])
y = df["selling_price"]

In [89]:
X

,km_driven,owner,Car_Age,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,seller_type_Individual,seller_type_Trustmark Dealer,transmission_Manual
0,70000,0,18,0,0,0,1,1,0,1
1,50000,0,18,0,0,0,1,1,0,1
2,100000,0,13,1,0,0,0,1,0,1
3,46000,0,8,0,0,0,1,1,0,1
4,141000,2,11,1,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...
4335,80000,2,11,1,0,0,0,1,0,1
4336,80000,2,11,1,0,0,0,1,0,1
4337,83000,2,16,0,0,0,1,1,0,1
4338,90000,0,9,1,0,0,0,1,0,1
4339,40000,0,9,0,0,0,1,1,0,1

In [90]:
y

0        60000
1       135000
2       600000
3       250000
4       450000
         ...
4335    409999
4336    409999
4337    110000
4338    865000
4339    225000
Name: selling_price, Length: 4340, dtype: int64

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [92]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [93]:
y_pred = model.predict(X_test)
y_pred

array([ 4.24067873e+05,  5.04287763e+05,  7.25279817e+04,  4.88505118e+05,
        1.53365585e+06,  2.40569237e+05,  4.46360257e+05,  2.70751512e+05,
        6.64088008e+05,  3.09359958e+05,  7.01675431e+05,  5.99617730e+05,
        5.99448450e+05,  7.92731698e+04,  7.17219824e+05,  4.50042202e+05,
        8.54594497e+05,  1.34789577e+06,  9.80858501e+04,  1.48857346e+06,
        6.61867089e+05,  7.44536903e+05,  4.59889787e+05,  7.64957359e+05,
        3.51439006e+05,  6.35847524e+05,  7.06759060e+05,  2.61035279e+05,
        4.08344652e+05,  5.27771287e+05, -4.68333228e+04,  1.44429464e+06,
        6.13900502e+05,  7.29748589e+05,  5.06329808e+05,  4.65896776e+05,
        7.80272702e+05,  4.70100015e+05,  1.05905878e+05,  4.91541494e+05,
        6.05216840e+05,  4.68568481e+05,  7.18517338e+05,  4.51602457e+05,
        4.13688365e+05,  3.67248343e+05,  3.99682474e+05,  4.81536832e+05,
        7.24116447e+05,  4.76285877e+05,  2.39653526e+05,  3.09865500e+05,
        5.71535725e+05,  2.63425479e+05,  4.02397389e+05,  8.65121896e+05,
        6.77676426e+05,  2.03155422e+05,  2.92968968e+05,  4.29198906e+05,
        7.42672663e+03,  4.73716804e+05,  1.32896364e+06,  7.47588424e+05,
       -2.78350141e+03,  3.51200408e+05,  5.71535725e+05,  1.15916992e+05,
        1.83878458e+05,  5.24767944e+05,  1.29418423e+06,  4.57005592e+05,
       -2.32039575e+04,  1.48721583e+06,  2.97178957e+05,  7.88429336e+05,
        3.07144246e+05,  9.52976465e+05,  4.87445855e+05,  7.15451911e+05,
        5.24767944e+05,  2.54569828e+04,  1.80755665e+05,  5.11843332e+05,
       -1.55522702e+05,  4.53296348e+05,  3.07144246e+05,  2.03706920e+05,
        3.81831092e+05, -2.42972917e+05,  4.73875758e+05,  2.28183676e+05,
        2.01176121e+05,  1.75156555e+05,  3.92535315e+05,  4.73716804e+05,
        1.78252995e+06,  2.60949164e+05, -7.88861544e+03,  5.98102216e+05,
        5.15519014e+05,  6.69422658e+05,  5.45236836e+04,  2.69024588e+05,
        3.21410935e+05,  8.26712723e+05,  4.85415357e+05,  3.39007859e+05,
        3.82325087e+05,  5.30036572e+05,  3.30223788e+05,  4.55300153e+05,
        1.53758256e+06,  6.15870578e+05,  4.21617948e+05,  9.69126464e+04,
        3.00141617e+05,  1.70376156e+05,  1.65902975e+06,  6.66935310e+05,
        7.98231155e+05,  4.45812460e+05,  2.58728245e+05,  7.59852245e+05,
        1.36642002e+06, -2.40582717e+05,  7.37601762e+04,  1.34229666e+06,
        2.22617600e+05,  2.53215251e+05,  8.81061083e+05,  7.28727566e+05,
        5.92662401e+05, -1.35102246e+05,  1.40307204e+06,  1.52839335e+06,
        6.51656861e+05,  3.35885065e+05,  5.62980058e+05,  4.12955771e+05,
        6.15870578e+05,  9.45851907e+04,  5.09946597e+05,  3.63452681e+05,
        8.65121896e+05, -3.74982768e+04,  5.21032007e+05,  3.70626533e+05,
        6.54214386e+05,  4.37487011e+05,  6.55973951e+05,  1.98224192e+05,
        7.80272702e+05,  1.36008832e+06,  4.37487011e+05,  5.01224694e+05,
        7.04738499e+05,  9.56956502e+04,  3.96619406e+05,  5.20156825e+05,
        7.88092730e+05,  6.05216840e+05,  5.43988504e+05, -4.46124037e+04,
        3.76725978e+05,  4.06541205e+05,  6.30487154e+05,  4.73720932e+05,
        5.94658570e+04,  2.32360638e+04,  9.32193348e+04,  1.86354774e+05,
       -1.29937295e+04,  2.99655272e+05,  4.10234517e+05,  5.61968579e+05,
        5.22666173e+05,  3.89531972e+05,  2.04891306e+05,  6.42983136e+05,
        3.16860479e+05,  1.32951736e+06,  8.42598500e+05,  4.07850657e+05,
       -1.90868336e+04,  4.02584547e+05,  1.70545437e+05,  8.30700521e+05,
       -1.86153387e+05,  1.51869364e+06,  5.04347488e+05,  1.39631811e+06,
        7.50663040e+05,  3.25180842e+05,  2.27420687e+04,  6.04538471e+04,
        4.55517267e+05,  3.01371475e+05,  1.57155079e+06,  5.26750265e+05,
        1.60319449e+06,  6.17647987e+05,  5.02620564e+05,  4.80718123e+05,
        2.19206377e+05,  5.40577281e+05, -6.50328598e+04,  5.24975708e+04,
        5.26750265e+05,  7.75167588e+05,  1.44766401e+06,  1.35692759e+06,
        5.50787509e+05,  1.62904282e+05,  3.30779951e+05, -5.14444418e+04,
        2.49646640e+05,  3.46997168e+05,  1.40307204e+06,  3.51200408e+05,
        7.59852245e+05,  9.56956502e+04, -1.10451858e+05,  4.49185564e+05,
        3.83210445e+05, -7.70418979e+03,  1.65646565e+06,  5.14861290e+05,
        6.90704541e+05,  4.76107004e+05,  1.90965893e+05,  9.80223667e+04,
        6.67466198e+05,  4.89499449e+05,  2.14101263e+05,  9.13713181e+05,
        1.50124980e+05,  1.46746790e+05,  6.67466198e+05,  4.95125250e+05,
        3.31366704e+05,  7.84252149e+04,  3.61818515e+05,  3.97640429e+05,
        1.44356591e+05,  6.82287545e+05,  6.57255970e+05,  2.62801138e+05,
        5.09452602e+05,  3.97640429e+05,  3.69209912e+05,  1.71670103e+06,
        3.61410636e+05,  3.92535315e+05,  8.81061083e+05,  3.01371475e+05,
        7.42010884e+04,  3.59592208e+05,  5.53316634e+05,  2.31279777e+05,
        6.96604190e+05,  3.66504202e+05,  1.40307204e+06,  1.40213184e+04,
        2.15497132e+05,  4.13688365e+05,  6.58792473e+05,  3.90454009e+04,
        1.48052443e+06,  1.52362416e+05,  6.42983136e+05,  4.78327923e+05,
        3.82325087e+05,  6.96760850e+04,  4.01257218e+05,  1.71159591e+06,
        7.37905224e+05,  4.20005267e+05,  8.66878422e+05,  6.05216840e+05,
        1.41264923e+06,  4.05868336e+05,  6.02826640e+05,  3.67248343e+05,
       -2.78350141e+03,  4.08344652e+05,  6.72077317e+05,  3.12461266e+05,
       -6.50328598e+04, -1.29937295e+04, -1.83932468e+05,  6.57015575e+05,
       -2.78350141e+03,  3.80574108e+04,  7.50963206e+04,  7.28727566e+05,
        3.15464609e+05,  3.51200408e+05,  1.40307204e+06,  1.54164516e+06,
        1.40768497e+06, -3.10239857e+04, -1.73722239e+05,  1.64320887e+06,
        9.56956502e+04,  5.48566590e+05, -9.32733441e+04,  9.76535409e+05,
        7.90482930e+05,  3.99036298e+05,  5.22547025e+05,  8.31806289e+05,
        3.90145115e+05,  4.23898593e+05,  3.60943333e+05,  9.51844360e+05,
        5.95006612e+05,  4.19287474e+05,  4.23898593e+05,  1.41264923e+06,
        4.88538151e+05,  6.26068031e+05,  1.61871587e+06,  2.83845935e+05,
       -3.45246451e+04,  2.88351728e+04,  6.66118506e+05,  7.75167588e+05,
        2.51166865e+05,  3.41670044e+05,  8.98199792e+05,  2.79967410e+05,
        4.33224046e+05,  7.76177063e+05,  1.21100612e+06, -2.55941574e+04,
        1.70700925e+04,  4.04635408e+05,  5.67064149e+05,  2.22584567e+05,
        4.60297667e+05,  1.34315643e+05,  4.55479027e+05,  4.82939042e+05,
        3.43705094e+05,  4.06856327e+05,  5.46176390e+05,  5.09946597e+05,
        7.39390497e+04,  5.23687196e+05,  4.57990548e+05,  4.88841725e+05,
        7.62073165e+05,  4.64994901e+05,  1.85319500e+05,  9.52976465e+05,
        6.68014711e+05,  2.47821708e+05,  4.16078565e+05,  5.20624128e+05,
        1.41556119e+06,  2.14509142e+05,  6.90107573e+05,  2.43005023e+05,
        2.88918196e+05,  1.33406875e+06,  2.65685707e+05,  6.45564461e+05,
        6.61867089e+05,  5.79669871e+05,  4.55686548e+05,  4.19456755e+05,
        5.54816844e+05,  3.10767375e+05,  4.94631255e+05,  2.69024588e+05,
        5.31242235e+05,  6.36341519e+05,  5.89238222e+05,  3.61410636e+05,
        6.69214607e+05,  3.04998985e+05,  2.46053661e+05,  4.24740742e+05,
        4.32338688e+05,  4.01257218e+05,  1.43246179e+06,  2.76758501e+05,
        8.05781619e+05,  1.49061551e+06,  5.99112188e+05,  2.32794795e+05,
        6.59298016e+05,  6.82287545e+05,  1.45398938e+06,  7.65966835e+05,
        6.72800726e+05,  5.14502960e+05,  2.85132424e+05,  3.17354474e+05,
        5.95006612e+05,  1.41264923e+06,  4.57413472e+05,  6.98096882e+05,
        6.15427068e+05,  4.66531404e+05, -5.14444418e+04,  3.33408750e+05,
        5.99112188e+05,  1.23263266e+05,  5.70910473e+05,  4.50087439e+05,
        6.24927548e+05,  3.69767361e+05,  5.34978172e+05,  4.75205129e+05,
        1.54242104e+05,  2.87054844e+05,  7.28727566e+05,  1.63674613e+06,
        4.47697239e+05,  2.53215251e+05,  5.22332162e+05,  4.79783216e+05,
        1.41163345e+06,  6.23247096e+05,  4.34248885e+05, -2.32039575e+04,
        1.56173895e+06,  5.95006612e+05,  3.23198522e+05,  1.28270061e+06,
       -6.50328598e+04,  5.16782903e+05,  6.75140385e+05,  1.39733913e+06,
        2.01908714e+05,  6.53687359e+05,  6.03690274e+05,  6.22068684e+05,
       -7.39462037e+03,  5.87017303e+05,  1.08049166e+04,  5.79197274e+05,
        3.51367733e+05,  4.21291279e+05,  3.89683282e+05,  1.50488834e+06,
        5.30367053e+05,  1.65678921e+05,  7.08307110e+05,  1.05905878e+05,
        4.71981624e+05,  1.30192179e+05,  2.27195686e+05,  2.39626833e+05,
        3.69230664e+05,  6.15427068e+05,  2.58558964e+05,  4.19508724e+05,
        4.57907467e+05,  4.54784673e+05,  5.13170132e+05, -2.34489613e+05,
        4.84190130e+05,  4.94137260e+05,  5.66962047e+05,  5.74586155e+05,
        6.20038187e+05,  5.27244260e+05,  3.42649006e+05,  3.75237652e+05,
        2.95423427e+05,  8.21607609e+05,  3.12253727e+04,  6.72077317e+05,
        1.80755665e+05,  6.43460133e+05,  3.01371475e+05, -5.54027424e+04,
        3.46033126e+05,  5.58607538e+05,  1.36536562e+05,  5.37368372e+05,
        3.15464609e+05, -6.74230597e+04,  7.13699764e+04,  8.17819298e+05,
        4.60467197e+04,  2.95044153e+05,  5.64375927e+05,  2.35015714e+05,
        1.33917387e+06,  1.33641711e+06,  7.42494858e+05,  8.11397381e+05,
        2.42499480e+05,  5.60997737e+05,  6.15427068e+05,  6.87886654e+05,
       -1.36918676e+05, -5.94337507e+04,  4.79603690e+05,  6.23464243e+05,
        5.46349788e+05,  7.75167588e+05,  6.25556180e+04,  3.96646099e+05,
        5.30367053e+05,  3.25180842e+05,  5.00263397e+05,  1.32896364e+06,
        2.19206377e+05,  6.69422658e+05,  2.68036598e+05,  4.90520471e+05,
        5.84796383e+05,  4.14356008e+04,  1.62382098e+06,  1.76517154e+06,
        1.53247774e+05,  3.20075728e+05,  6.35847524e+05,  5.40384687e+05,
        5.83411935e+05,  6.51656861e+05,  6.25637296e+05,  4.64994901e+05,
        5.40223651e+05,  3.21769620e+05,  9.24867410e+04,  4.78327923e+05,
        2.12539968e+05,  5.97227531e+05,  1.61614680e+06,  3.64213343e+05,
        7.54747131e+05, -7.98542068e+04,  7.28727566e+05,  6.07082689e+05,
        4.68117695e+05,  7.80103421e+05,  5.58776818e+05,  2.74368301e+05,
        2.66988183e+05,  4.94137260e+05,  2.21596577e+05,  2.44894888e+05,
        2.97265072e+05,  8.89914192e+05, -8.30631160e+04,  5.20580755e+03,
        3.14970614e+05,  9.52976465e+05,  5.27158144e+05,  2.19802503e+05,
        1.31925443e+05,  7.38003242e+05,  2.74368301e+05,  3.98134424e+05,
        6.60834518e+05,  1.60293889e+06,  3.07823455e+05,  1.30903314e+06,
        5.34978172e+05, -5.99241062e+03,  8.58257560e+05,  3.02212798e+05,
        1.30258357e+04,  4.21617948e+05,  1.32636597e+06,  6.66130166e+04,
        1.64185124e+06,  3.83861590e+05,  6.72077317e+05,  4.96358179e+05,
        2.47718244e+05,  4.52308358e+05,  2.73635707e+05,  4.18554880e+05,
        1.28716534e+05,  4.78327923e+05,  7.00261314e+05,  5.53177709e+05,
        3.65027424e+05,  1.60165928e+05,  2.88351728e+04,  6.50657323e+05,
        4.08089256e+05,  4.86317232e+05,  8.27834510e+05,  5.32587972e+05,
        3.10560919e+04,  3.82325087e+05,  1.70545437e+05,  2.06111954e+05,
        6.18560569e+04,  5.26546060e+05,  4.85415357e+05,  1.48283040e+06,
        3.46844588e+05,  3.56305522e+05,  3.67536772e+05,  2.58728245e+05,
        4.37487011e+05,  1.33726203e+02,  3.20977603e+05,  3.97640429e+05,
        4.80298696e+05,  2.86933372e+05,  3.68546247e+05,  1.62377254e+05,
        7.83106744e+05, -1.36918676e+05,  6.24449710e+05,  7.24116447e+05,
        8.01187153e+05,  9.13598207e+05,  4.70100015e+05,  4.75720609e+05,
        5.66596846e+05,  8.54268791e+05,  7.02708001e+05,  1.84229600e+06,
        4.08344652e+05,  6.15427068e+05,  7.52751941e+04,  3.15464609e+05,
       -1.06019613e+05,  5.40577281e+05,  1.52430926e+06,  3.83226961e+05,
        7.93308804e+05,  4.84394334e+05,  5.34978172e+05,  2.07154194e+05,
        6.99633385e+05,  2.47553974e+05,  4.42098130e+05, -1.91752496e+05,
        6.35847524e+05,  4.80310243e+05,  2.12374339e+05,  5.93191096e+05,
        8.19283587e+04,  4.88538151e+05,  2.30404595e+05,  4.08648925e+04,
        8.14460449e+05,  3.61410636e+05,  1.64946327e+05,  5.79027994e+05,
        3.48866719e+05,  3.25359716e+05,  2.22584567e+05,  2.74023559e+05,
        5.16540036e+05,  3.68528084e+05,  5.92986051e+05,  5.56386618e+05,
        4.67192454e+05,  4.81319718e+05,  4.08648925e+04,  7.14612120e+05,
        2.65994552e+05,  2.40984462e+05,  4.08648925e+04,  7.96597519e+05,
        2.32360638e+04,  5.38667479e+04,  1.30854318e+06,  3.10262362e+05,
        5.52689032e+05,  1.41264923e+06,  1.47734781e+05, -1.53839293e+04,
        1.26885843e+06,  3.77627852e+05,  3.97640429e+05,  1.37387709e+06,
        2.89446770e+05,  7.70062473e+05,  2.19696137e+05,  2.94550158e+05,
        4.64994901e+05,  6.14584918e+05,  4.24153989e+05,  6.17951561e+05,
        2.78471827e+04,  4.59889787e+05,  8.11397381e+05,  7.98231155e+05,
        1.65848202e+05,  8.57837402e+05,  4.80310243e+05,  7.64957359e+05,
        4.05868336e+05,  6.20532182e+05, -7.98542068e+04,  3.97317606e+05,
        7.60861721e+05,  4.65896776e+05,  3.34396740e+05,  1.58606462e+06,
        1.11504987e+05,  3.72429883e+05,  4.02745543e+05,  7.41989315e+05,
       -9.10524250e+04,  7.38937794e+05,  6.69214607e+05,  1.45897535e+06,
        2.64446502e+05,  5.07556397e+05,  4.07345114e+05,  5.14497991e+05,
        6.05216840e+05,  3.57240429e+05,  2.83872628e+05,  4.31887902e+05,
        3.11586084e+05, -3.66230948e+04,  6.87392659e+05,  1.47700561e+06,
        5.48072595e+05, -1.06035296e+04,  5.16540036e+05,  1.76369547e+04,
        4.31301149e+05,  5.64375927e+05,  6.50649661e+04,  4.94485414e+05,
        1.23920639e+06,  8.81061083e+05,  1.41556119e+06,  6.35353529e+05,
        3.46568912e+05,  4.36427748e+05,  1.29786565e+06,  2.86943007e+04,
        5.86529074e+05,  2.27195686e+05,  4.80310243e+05,  7.65098124e+05,
        1.34315643e+05,  5.23007058e+05,  2.53215251e+05,  4.67192454e+05,
        2.63425479e+05,  5.29801785e+05,  6.52711081e+05,  5.02126569e+05,
        4.70347099e+04,  1.07802083e+05,  5.08768186e+05,  2.55436170e+05,
        5.50114641e+05, -2.66602282e+05,  1.49136990e+05,  9.13713181e+05,
        1.60748462e+06,  4.82694103e+05,  5.34978172e+05,  8.20753912e+05,
       -6.96439788e+04,  1.31746544e+06,  9.16518149e+05,  3.56305522e+05,
        1.57945009e+05,  1.44525871e+05, -4.36244136e+04,  1.54242104e+05,
        6.69193122e+05,  6.69214607e+05,  6.96760850e+04,  1.88575693e+05,
        4.59889787e+05,  7.77198085e+05,  7.36547594e+05,  1.68155237e+05,
        5.63387937e+05,  1.98785921e+05,  3.40484637e+05,  2.64446502e+05,
        4.87457403e+05, -7.08108424e+04,  6.18560569e+04,  2.50825051e+05,
        3.65027424e+05,  3.22790642e+05, -9.52259529e+04,  7.98231155e+05,
        4.71981624e+05,  5.14557716e+05,  4.96635060e+05,  7.85377816e+05,
       -9.61553945e+03,  4.86946892e+05, -1.54703993e+05,  8.54854222e+04,
        5.56386618e+05,  5.49060585e+05,  1.00306769e+05,  4.73163084e+05,
        6.79897345e+05,  3.71272709e+05,  2.86943007e+04,  6.64930157e+05,
       -1.34114256e+05,  5.11434922e+05,  8.39974472e+05,  4.00897638e+05,
        5.97478551e+05,  1.51869364e+06,  4.27732537e+05,  1.20545291e+06,
        8.47740371e+05,  4.59889787e+05,  3.89516675e+05,  7.34853703e+05,
        6.97602887e+05,  7.06114838e+05, -7.39462037e+03,  2.85914527e+05,
        5.58776818e+05,  1.65848202e+05,  4.13509491e+05,  1.51869364e+06,
        1.35426103e+05,  1.87256648e+05,  5.10327784e+05,  6.46046204e+05,
        4.22638971e+05,  1.43408441e+06,  5.90595851e+05,  2.38138508e+05,
        3.03233821e+05,  2.56338045e+05,  6.79897345e+05,  3.25674837e+05,
        7.74961132e+04,  5.26750265e+05, -2.93732307e+05,  4.60128386e+05,
        5.19662830e+05,  5.30630151e+05,  8.21607609e+05,  2.87424484e+05,
        5.79197274e+05,  7.59852245e+05,  2.91665963e+05,  4.81451694e+04,
        8.16502495e+05,  6.26068031e+05, -8.78435158e+04,  1.36723548e+06,
        5.48566590e+05,  1.44356591e+05,  1.80913420e+06, -1.65902211e+05,
        1.84229600e+06,  2.56215575e+05, -5.00442050e+03, -5.62582332e+02,
        5.64375927e+05,  4.82939042e+05,  6.93882486e+05,  5.75220784e+05])

In [94]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [95]:
print(f"Mean Absolute Error: {mae:.2f}")
print(f"Mean Squared Error: {mse:.2f}")
print(f"RÂ² Score: {r2:.2f}")

Mean Absolute Error: 222105.55
Mean Squared Error: 182521565071.41
RÂ² Score: 0.40