In [99]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from datetime import datetime

In [100]:
df = pd.read_csv('./car data.csv')
df

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Driven_kms     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Selling_type   301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [102]:
df["Car_Age"] = datetime.now().year - df["Year"]
df.drop(columns=["Year", "Car_Name"], inplace=True)
df

,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner,Car_Age
0,3.35,5.59,27000,Petrol,Dealer,Manual,0,11
1,4.75,9.54,43000,Diesel,Dealer,Manual,0,12
2,7.25,9.85,6900,Petrol,Dealer,Manual,0,8
3,2.85,4.15,5200,Petrol,Dealer,Manual,0,14
4,4.60,6.87,42450,Diesel,Dealer,Manual,0,11
...,...,...,...,...,...,...,...,...
296,9.50,11.60,33988,Diesel,Dealer,Manual,0,9
297,4.00,5.90,60000,Petrol,Dealer,Manual,0,10
298,3.35,11.00,87934,Petrol,Dealer,Manual,0,16
299,11.50,12.50,9000,Diesel,Dealer,Manual,0,8
300,5.30,5.90,5464,Petrol,Dealer,Manual,0,9

In [103]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Selling_Price  301 non-null    float64
 1   Present_Price  301 non-null    float64
 2   Driven_kms     301 non-null    int64
 3   Fuel_Type      301 non-null    object
 4   Selling_type   301 non-null    object
 5   Transmission   301 non-null    object
 6   Owner          301 non-null    int64
 7   Car_Age        301 non-null    int64
dtypes: float64(2), int64(3), object(3)
memory usage: 18.9+ KB

In [104]:
# df['Fuel_Type'].unique()

array(['Petrol', 'Diesel', 'CNG'], dtype=object)

In [105]:
# df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Selling_Price  301 non-null    float64
 1   Present_Price  301 non-null    float64
 2   Driven_kms     301 non-null    int64
 3   Fuel_Type      301 non-null    object
 4   Selling_type   301 non-null    object
 5   Transmission   301 non-null    object
 6   Owner          301 non-null    int64
 7   Car_Age        301 non-null    int64
dtypes: float64(2), int64(3), object(3)
memory usage: 18.9+ KB

In [106]:
# df = pd.get_dummies(df, columns=["Fuel_Type"], drop_first=True).astype(int)
# df

ValueError: invalid literal for int() with base 10: 'Dealer'

In [ ]:
# df = pd.get_dummies(df, columns=["Transmission"], drop_first=True).astype(int)
# df

KeyError: "None of [Index(['Transmission'], dtype='object')] are in the [columns]"

In [ ]:
# df = pd.get_dummies(df, columns=["Selling_type"], drop_first=True).astype(int)
# df

,Selling_Price,Present_Price,Driven_kms,Owner,Car_Age,Fuel_Type_Diesel,Fuel_Type_Petrol,Transmission_Manual,Selling_type_Individual
0,3,5,27000,0,11,0,1,1,0
1,4,9,43000,0,12,1,0,1,0
2,7,9,6900,0,8,0,1,1,0
3,2,4,5200,0,14,0,1,1,0
4,4,6,42450,0,11,1,0,1,0
...,...,...,...,...,...,...,...,...,...
296,9,11,33988,0,9,1,0,1,0
297,4,5,60000,0,10,0,1,1,0
298,3,11,87934,0,16,0,1,1,0
299,11,12,9000,0,8,1,0,1,0
300,5,5,5464,0,9,0,1,1,0

In [ ]:
# df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Selling_Price  301 non-null    float64
 1   Present_Price  301 non-null    float64
 2   Driven_kms     301 non-null    int64
 3   Fuel_Type      301 non-null    object
 4   Selling_type   301 non-null    object
 5   Transmission   301 non-null    object
 6   Owner          301 non-null    int64
 7   Car_Age        301 non-null    int64
dtypes: float64(2), int64(3), object(3)
memory usage: 18.9+ KB

In [107]:
df = pd.get_dummies(df, columns=["Fuel_Type", "Selling_type", "Transmission"], drop_first=True).astype(int)
df

,Selling_Price,Present_Price,Driven_kms,Owner,Car_Age,Fuel_Type_Diesel,Fuel_Type_Petrol,Selling_type_Individual,Transmission_Manual
0,3,5,27000,0,11,0,1,0,1
1,4,9,43000,0,12,1,0,0,1
2,7,9,6900,0,8,0,1,0,1
3,2,4,5200,0,14,0,1,0,1
4,4,6,42450,0,11,1,0,0,1
...,...,...,...,...,...,...,...,...,...
296,9,11,33988,0,9,1,0,0,1
297,4,5,60000,0,10,0,1,0,1
298,3,11,87934,0,16,0,1,0,1
299,11,12,9000,0,8,1,0,0,1
300,5,5,5464,0,9,0,1,0,1

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Selling_Price            301 non-null    int64
 1   Present_Price            301 non-null    int64
 2   Driven_kms               301 non-null    int64
 3   Owner                    301 non-null    int64
 4   Car_Age                  301 non-null    int64
 5   Fuel_Type_Diesel         301 non-null    int64
 6   Fuel_Type_Petrol         301 non-null    int64
 7   Selling_type_Individual  301 non-null    int64
 8   Transmission_Manual      301 non-null    int64
dtypes: int64(9)
memory usage: 21.3 KB

In [109]:
X = df.drop(columns=["Selling_Price"])
y = df["Selling_Price"]

In [110]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [111]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [113]:
y_pred = model.predict(X_test)
y_pred

array([ 2.54246597,  7.70201236,  6.00317389, -1.73320291,  8.66827203,
        6.7030152 ,  0.99578098,  0.33374687,  0.97801201,  6.77984236,
        8.41469564,  0.26955187,  8.18759974,  3.02663501,  6.43879503,
        2.43095107,  0.06406033, 10.22981168,  1.35310591,  1.8329767 ,
       -0.03252015,  7.62312863,  6.17768149,  2.02962714,  0.22656321,
        3.14505136,  4.65270167,  2.31908931,  1.77244946,  1.38726768,
       -0.05773983,  8.83873056, -1.15023596,  2.07032421,  7.90902222,
        4.26162138,  6.72861945,  7.16538074,  2.47920263,  7.58208713,
        3.54685068,  4.01956496,  3.92802476,  0.11937956,  6.75936858,
        0.27585679,  6.83615448, 10.75834409,  2.64867259,  4.74935494,
        6.40947463,  1.81595341, 20.03214221, 16.57124081,  7.01760879,
        9.20484834,  3.92606853,  8.40031752,  1.43579387,  7.131421  ,
       -0.14600872])

In [114]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [115]:
print(f"Mean Absolute Error: {mae:.2f}")
print(f"Mean Squared Error: {mse:.2f}")
print(f"RÂ² Score: {r2:.2f}")

Mean Absolute Error: 1.30
Mean Squared Error: 3.86
RÂ² Score: 0.84